### ISSUE TITLE
Index.js not found 

### ISSUE THREAD

**Issue by ManucrackYT** [Votion-Development/Dashactyl-Egg#14]
If I continue installing, it takes +10 min doing nothing

**Comment by WarrioR151** [comment]
Yes, i got stuck at
index.js not found. Proceed to install Dashactyl V2? (Y/N)
Y
Installing Dashactyl...
Cloning into '/home/container/Dashactyl-v2'...

**Comment by JamieGrimwood** [comment]
Fixed
