### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MRJ-Badshah** [Votion-Development/Dashactyl-Egg#6]
![IMG_20220531_161415](https://user-images.githubusercontent.com/69976020/171349367-3228031e-e505-49f2-996d-7b2f520ba8c4.jpg)

**Comment by blazecoding2009** [comment]
Free domain user.
![image](https://user-images.githubusercontent.com/56598575/171392962-0f96b1ed-2262-4de3-9764-16cedef8d717.png)
![image](https://user-images.githubusercontent.com/56598575/171393275-3bd70ad6-be82-46a5-9098-7a7d459f0359.png)

Advised not to provide support.

Even More Proof: https://panel.mrjbotlab.ml/auth/login

Same theme and the domain matches with the user's name.

**Comment by MRJ-Badshah** [comment]
Doesn't matter that i am using free domain matter error comming in egg

**Comment by blazecoding2009** [comment]
> Freenom domains and free trial based hosting are not supported here. You will not receive support for Dashactyl or be granted access to DashactylManager if you are using any of these services. Trying to bypass this rule will result in you being support-banned.

Clearly states that anything related with Freenom, you will not be given support.

**Comment by ItzKoolKid96** [comment]
skid trys to get support on a freenom domain and making an alt

**Comment by ItzKoolKid96** [comment]
this is not a reson to open a request like this just cuz you are mad that you got banned skid so yeah stop whit you free shity hosts on oracel and frenomdomain and go toch some grass

**Comment by devnote-dev** [comment]
@ItzKoolKid96 Do not respond if you have nothing useful to say.

**Comment by devnote-dev** [comment]
The error itself is likely an issue with connecting to the database from the panel. As stated before, Pterodactyl wasn't made for webhosting and I really don't care for the egg enough to purposefully go against this. If you have issues with the egg, fix it yourself or don't use it - we will likely deprecate and archive it in the future.
